
import '../models.dart';

class UserDevice {
    String id;
    int roleId;
    String roleName;
    bool isDefaultRole;
    String departmentId;
    String departmentName;
    String siteId;
    String siteName;
    dynamic fleetId;
    String nik;
    String name;
    String email;
    String phone;
    bool isActive;
    String imageUrl;
    String unitId;
    String unitCode;
    String unitTypeId;
    String unitCategoryId;
    int loginType;
    int loginStatus;
    DateTime loginAt;
    int lastTotalCycle;
    int lastTotalHauler;
    String lastCycleId;
    String lastActivityId;
    Last lastPit;
    LastHauler lastHauler;
    LastLoader lastLoader;
    Last lastLoadingPoint;
    Last lastDumpingPoint;
    Last lastMaterial;
    bool cycleFinished;
    bool isDisposal;

    UserDevice({
        required this.id,
        required this.roleId,
        required this.roleName,
        required this.isDefaultRole,
        required this.departmentId,
        required this.departmentName,
        required this.siteId,
        required this.siteName,
        required this.fleetId,
        required this.nik,
        required this.name,
        required this.email,
        required this.phone,
        required this.isActive,
        required this.imageUrl,
        required this.unitId,
        required this.unitCode,
        required this.unitTypeId,
        required this.unitCategoryId,
        required this.loginType,
        required this.loginStatus,
        required this.loginAt,
        required this.lastTotalCycle,
        required this.lastTotalHauler,
        required this.lastCycleId,
        required this.lastActivityId,
        required this.lastPit,
        required this.lastHauler,
        required this.lastLoader,
        required this.lastLoadingPoint,
        required this.lastDumpingPoint,
        required this.lastMaterial,
        required this.cycleFinished,
        required this.isDisposal,
    });

    factory UserDevice.fromJson(Map<String, dynamic> json) => UserDevice(
        id: json["id"],
        roleId: json["role_id"],
        roleName: json["role_name"],
        isDefaultRole: json["is_default_role"],
        departmentId: json["department_id"],
        departmentName: json["department_name"],
        siteId: json["site_id"],
        siteName: json["site_name"],
        fleetId: json["fleet_id"],
        nik: json["nik"],
        name: json["name"],
        email: json["email"],
        phone: json["phone"],
        isActive: json["is_active"],
        imageUrl: json["image_url"],
        unitId: json["unit_id"],
        unitCode: json["unit_code"],
        unitTypeId: json["unit_type_id"],
        unitCategoryId: json["unit_category_id"],
        loginType: json["login_type"],
        loginStatus: json["login_status"],
        loginAt: DateTime.parse(json["login_at"]),
        lastTotalCycle: json["last_total_cycle"],
        lastTotalHauler: json["last_total_hauler"],
        lastCycleId: json["last_cycle_id"],
        lastActivityId: json["last_activity_id"],
        lastPit: Last.fromJson(json["last_pit"]),
        lastHauler: LastHauler.fromJson(json["last_hauler"]),
        lastLoader: LastLoader.fromJson(json["last_loader"]),
        lastLoadingPoint: Last.fromJson(json["last_loading_point"]),
        lastDumpingPoint: Last.fromJson(json["last_dumping_point"]),
        lastMaterial: Last.fromJson(json["last_material"]),
        cycleFinished: json["cycle_finished"],
        isDisposal: json["is_disposal"],
    );

    Map<String, dynamic> toJson() => {
        "id": id,
        "role_id": roleId,
        "role_name": roleName,
        "is_default_role": isDefaultRole,
        "department_id": departmentId,
        "department_name": departmentName,
        "site_id": siteId,
        "site_name": siteName,
        "fleet_id": fleetId,
        "nik": nik,
        "name": name,
        "email": email,
        "phone": phone,
        "is_active": isActive,
        "image_url": imageUrl,
        "unit_id": unitId,
        "unit_code": unitCode,
        "unit_type_id": unitTypeId,
        "unit_category_id": unitCategoryId,
        "login_type": loginType,
        "login_status": loginStatus,
        "login_at": loginAt.toIso8601String(),
        "last_total_cycle": lastTotalCycle,
        "last_total_hauler": lastTotalHauler,
        "last_cycle_id": lastCycleId,
        "last_activity_id": lastActivityId,
        "last_pit": lastPit.toJson(),
        "last_hauler": lastHauler.toJson(),
        "last_loader": lastLoader.toJson(),
        "last_loading_point": lastLoadingPoint.toJson(),
        "last_dumping_point": lastDumpingPoint.toJson(),
        "last_material": lastMaterial.toJson(),
        "cycle_finished": cycleFinished,
        "is_disposal": isDisposal,
    };
}
